### PR TITLE
fix: create plugins directory

### LINKED ISSUE #2: Create the plugins directory
If the plugins directory does not exist under `~/.config/octant`, then while copying the binary over to plugins, a file is created, which makes octant error out, as plugins is not a directory but a file:
https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/loader.go#L128

In the makefile, we should create the plugins directory also.

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #2

### CODE REVIEW

**Comment by ankitm123** [comment]
Will rebase after #1 is merged into master, I think that will fix the issues with pr check.

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[jstrachan](https://github.com/jenkins-x/octant-jx/pull/3#issuecomment-660069653 "LGTM")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=jenkins-x%2Foctant-jx).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com#issuecomment-660069653/jenkins-x/octant-jx/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
