### PR TITLE
chore: enable linter

### LINKED ISSUE #4: Add linter
We should add golangci-lint to the codebase as part of a pr check.

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #4

### CODE REVIEW

**Comment by jstrachan** [comment]
looks great @ankitm123 - you happy to merge this yet? The `WIP` prefix made me assume no

**Comment by ankitm123** [comment]
Need to fix few more stuff, should be ready soon :)

**Comment by ankitm123** [comment]
All set @jstrachan, can me merged :)

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[jstrachan](https://github.com/jenkins-x/octant-jx/pull/11#issuecomment-663864674 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=jenkins-x%2Foctant-jx).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-663864674/jenkins-x/octant-jx/blob/master/OWNERS)~~ [jstrachan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
